artifact_location: file:///C:/Users/jra1029/week-1-intro-to-deep-rl-and-agent-training-environments-julialruiter/submission/mlflow/0
creation_time: 1694474953800
experiment_id: '0'
last_update_time: 1694474953800
lifecycle_stage: active
name: Default
