artifact_location: file:///C:/Users/jra1029/week-1-intro-to-deep-rl-and-agent-training-environments-julialruiter/submission/mlflow/969593667041879877
creation_time: 1694668579074
experiment_id: '969593667041879877'
last_update_time: 1694668579074
lifecycle_stage: active
name: penalty0.05
