artifact_location: file:///C:/Users/jra1029/week-1-intro-to-deep-rl-and-agent-training-environments-julialruiter/submission/mlflow/883204327884522111
creation_time: 1694667174111
experiment_id: '883204327884522111'
last_update_time: 1694667174111
lifecycle_stage: active
name: <my_experinemnt>
