artifact_location: file:///C:/Users/jra1029/week-1-intro-to-deep-rl-and-agent-training-environments-julialruiter/submission/mlflow/732112524682666532
creation_time: 1694474953818
experiment_id: '732112524682666532'
last_update_time: 1694474953818
lifecycle_stage: active
name: red
